name: CI with Local Docker Build

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional but recommended)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t vite-ci-image .

      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            vite-ci-image \
            sh -c "pnpm install && pnpm prettier --check . && pnpm lint && pnpm test"
