name: CI with Local Docker and npm

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vite-ci-image .

      - name: Run tests inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            vite-ci-image \
            sh -c "
              npm run prettier:check || exit 1
              npm run lint || exit 1
              npm test || exit 1
            "
